-- MySQL Script generated by MySQL Workbench
-- Fri Dec 23 11:41:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `id` INT NOT NULL,
  `userId` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Server`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Server` (
  `id` INT NOT NULL,
  `serverId` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `serverId_UNIQUE` (`serverId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wallpapers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wallpapers` (
  `id` INT NOT NULL,
  `name` VARCHAR(55) NOT NULL,
  `level` INT NOT NULL DEFAULT 0,
  `price` VARCHAR(45) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profils` (
  `id` INT NOT NULL,
  `profilId` INT NOT NULL,
  `xp` INT NOT NULL DEFAULT 0,
  `level` INT NOT NULL DEFAULT 1,
  `nameColor` VARCHAR(8) NOT NULL DEFAULT '0000FF',
  `barColor` VARCHAR(8) NOT NULL DEFAULT 'ADFF2F',
  `Wallpapers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `profilId_UNIQUE` (`profilId` ASC) VISIBLE,
  INDEX `fk_Profils_Wallpapers_idx` (`Wallpapers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profils_Wallpapers`
    FOREIGN KEY (`Wallpapers_id`)
    REFERENCES `mydb`.`Wallpapers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wallpapers_has_Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wallpapers_has_Profils` (
  `Wallpapers_id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  PRIMARY KEY (`Wallpapers_id`, `Profils_id`),
  INDEX `fk_Wallpapers_has_Profils_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  INDEX `fk_Wallpapers_has_Profils_Wallpapers1_idx` (`Wallpapers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Wallpapers_has_Profils_Wallpapers1`
    FOREIGN KEY (`Wallpapers_id`)
    REFERENCES `mydb`.`Wallpapers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Wallpapers_has_Profils_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `mydb`.`Profils` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Profils_has_Wallpapers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Profils_has_Wallpapers` (
  `id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  `Wallpapers_id` INT NOT NULL,
  INDEX `fk_Profils_has_Wallpapers_Wallpapers1_idx` (`Wallpapers_id` ASC) VISIBLE,
  INDEX `fk_Profils_has_Wallpapers_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `Profils_Wallpapers_Unique` (`Profils_id` ASC, `Wallpapers_id` ASC) VISIBLE,
  CONSTRAINT `fk_Profils_has_Wallpapers_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `mydb`.`Profils` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profils_has_Wallpapers_Wallpapers1`
    FOREIGN KEY (`Wallpapers_id`)
    REFERENCES `mydb`.`Wallpapers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Server_has_Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Server_has_Profils` (
  `id` INT NOT NULL,
  `Server_id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  INDEX `fk_Server_has_Profils_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  INDEX `fk_Server_has_Profils_Server1_idx` (`Server_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Server_Profils_Unique` (`Server_id` ASC, `Profils_id` ASC) VISIBLE,
  CONSTRAINT `fk_Server_has_Profils_Server1`
    FOREIGN KEY (`Server_id`)
    REFERENCES `mydb`.`Server` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Server_has_Profils_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `mydb`.`Profils` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_makes_Profils`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_makes_Profils` (
  `id` INT NOT NULL,
  `Users_id` INT NOT NULL,
  `Profils_id` INT NOT NULL,
  INDEX `fk_Users_has_Profils_Profils1_idx` (`Profils_id` ASC) VISIBLE,
  INDEX `fk_Users_has_Profils_Users1_idx` (`Users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Users_Profils_Unique` (`Profils_id` ASC, `Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_has_Profils_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `mydb`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Profils_Profils1`
    FOREIGN KEY (`Profils_id`)
    REFERENCES `mydb`.`Profils` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;